Dear imgui (#127)
* first working version in dear/hello imgui

* temporarily disabling auto-run workflows

* Update ci-mac.yml

* Update ci-linux.yml

* Update ci-mac.yml

* Update ci-linux.yml

* Update CMakeLists.txt

* Update pfm.h

* Update CMakeLists.txt

* #include <cstring> for linux

* Update fwd.h

* Update ci-emscripten.yml

* Update ci-windows.yml

* Update ci-emscripten.yml

* Update app.cpp

* histogram

* fixed sRGB; work on histogram, pixel info and grid

* clean up coordinate systems, document HDRViewApp

* turn workflows on for push again

* fixing build errors on windows and emscripten

* clipping drawing to image viewport; improving statusbar

* adding info window

* image info window

* refactoring file_info window

* hover color and min,avg,max stats on histogram; normalize exposure ignores alpha

* Update image_gui.cpp

* todo list, working on channel statistics

* fixing channel hotkeys, button padding

* spdlog window

* work on spdlog window

* preprend log level icon on all spdlog window messages

* adding spdlog flag for log level icon

* hover and copy-to-clipboard support in SpdLogWindow

* stats about infinities

* many improvements

- fix slow parallel_for over all pixels
- consolidate setting primary and secondary texture
- remove non-working deferred load font code
- fix icon font sizes on non-retina screens
- add glfw drop event to open files
- made logging a bit less verbose
- add filtering to image list, support for visible/hidden images
- switch channel checkbox to button
- add busy progress bar widget
- adding async and progress files for future parallel work
- turn off openexr threading in cmake when building for emscripten

* working on linux ci build

* IconButton, rearranging HDRViewApp initialization

* adding hyperlinks

* working on async pixel stats, and emscripten threads

* avoiding histogram recompute, unbiased de-quantization

* multi-image load

* removing last HelloImGui::Log use

* fixing histogram blocking

* simplifying histogram logic

* asynchronous image loading

* new thread pool

* fixing build issues and seg faults

* AsyncTask rewritten in terms of new Scheduler

* fixing crashes, threadpool, histograms

- emscripten needs to have exception enabled
- async task has proper shared state so it can be detached (with the scheduler/threadpool cleaning it up)

* Scheduler propagates exceptions; snake_casing

* Update image.cpp

* small refactor of PixelStats

* minor tweaks

* Fix emscripten compil (cast window size to float) (#120)

This fixes the following error:

```
[ 82%] Building CXX object CMakeFiles/HDRView.dir/src/app.cpp.o
hdrview/src/app.cpp:1592:27: error: non-constant-expression cannot be narrowed from type 'int' to 'float' in initializer list [-Wc++11-narrowing-const-reference]
 1592 |     display_size = float2{window_width(), window_height()};
      |                           ^~~~~~~~~~~~~~
hdrview/src/app.cpp:1592:43: error: non-constant-expression cannot be narrowed from type 'int' to 'float' in initializer list [-Wc++11-narrowing-const-reference]
 1592 |     display_size = float2{window_width(), window_height()};
      |                                           ^~~~~~~~~~~~~~~
```

* can now drag onto app icon on macos

using Tom94's glfw fork on macOS

* trying to fix build

* Update app.cpp

* link statically against freetype on macOS

* Update ci-mac.yml

* Update CMakeLists.txt

* Update release.yml

* Update release.yml

* updating to most recent file browser lib

* including more recent versions of macOS

* updating workflows to latest versions

* Update ci-emscripten.yml

* Update ci-emscripten.yml

* updating to latest versions

* Update CMakeLists.txt

* Update ci-emscripten.yml

* Update texture_gl.cpp

* Update release.yml

* Update release.yml

* Update release.yml

* fixing workflows

* trying to fix emscripten

* trying to fix emscripten texturing error

* updating imgui_bundle + pinch to zoom support

* mac and emscripten fixes

- fix crash on startup on macOS
- check whether host platform is mac to enable apple-style shortcuts
- allow opening all image mime types on iOS/iPadOS

* working on key chords

* adding command palette

* Update app.cpp

* menu and command palette improvements

* replacing help/theme menu with command palette

* simplifying; fixed image and channel shortcuts

* adding icon and shortcut support to command palette

* fixing menu item alignment

* Cmd+. for escape on iOS, and fixing Cmd+P not working

* simplying help window

* fixing dpi issues in emscripten/windows

* fixing global shortcuts

* workaround for repeated shortcuts on emscripten

* minor tweaks; build-time version numbers

* improvements to command palette

* command palette checkmark and arrow indicators, fixing clicking, making it a popup

* adding restore layout and dockable windows to command palette

* Create ci-pages-deploy.yml

* Update ci-pages-deploy.yml

* can browse recent files in command palette

* Update app.cpp

* merging workflows

* detecting apple hardware via user agent

* using hello imgui's builtin font awesome 6

* about dialog tweaks

* working on fonts

* working on fonts

* multiple icon set support

* material design and material design icons

* debugging safari exr conversion

* replacing variable Material Symbol font with fixed

* Update fonts.h

* gui tweaks

* fixing fonts too big for ios

* Update hdrview.cpp

* adding Pillow package

* load only the icon glyphs we use

* Windows support (#125)

* fix crash / undef behavior on load recent

* heed dpi scaling in font lookup

* console and cmd line args on Windows

* unicode filenames on Windows

* fix C++20 compile error

* prevent shortcut-clash on Windows

Win+i is the system-wide shortcut to launch / switch to the i-th app in the taskbar

* fixing fmtlib compile errors

- removing custom linalg formatters, and relying on fmtlib's range-based formatters instead

* remove debug junk

* fixing broken merge

* fixing emscripten via backported fmtlib patch

---------

Co-authored-by: Wojciech Jarosz <wkjarosz@users.noreply.github.com>

* using EV+- icon

* switching back to C++17

* enable/disable dithering via command palette

* toggle dither on/off

* updating readme and screenshots

---------

Co-authored-by: Pascal Thomet <pthomet@gmail.com>
Co-authored-by: Pascal Grittmann <grittmann@cg.uni-saarland.de>